name: pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: gh release list --json name --limit 1 --jq '.[].name' > "$GITHUB_OUTPUT"
        id: last-release

      - run: echo ${{ steps.last-release }}
