name: pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: (echo -n 'name='; gh release list --json name --limit 1 --jq '.[].name') > "$GITHUB_OUTPUT"
        id: last-release
        env:
          GH_TOKEN: ${{ github.token }}

      - run: echo ${{ steps.last-release.outputs.name }}
