name: pages

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: (echo -n 'name='; gh release list --json name --limit 1 --jq '.[].name') > "$GITHUB_OUTPUT"
        id: last-release
        env:
          GH_TOKEN: ${{ github.token }}

      - run: gh release download ${RELEASE} -D _site
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE: ${{ steps.last-release.outputs.name }}

      - uses: actions/upload-pages-artifact@v3

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v4
